# tutorial https://alysivji.github.io/php-mysql-docker-containers.html

version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpassword
    ports:
      - "9906:3306"
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - wpsite

  # Web
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db                          #docker exec -it instance_name bash
    volumes:    #dar permisos luego chmod 755 -R /var/www/html/  entrando en la instancia
      - "./:/var/www/html"
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data:

#chmod -R 775 html
#chown -R www-data:www-data /var/www/html
#sudo chown -R $USER ~/.blabla
