# Read more about setting it up
# https://medium.com/@ljmocic/deploying-react-application-to-aws-s3-using-github-actions-85addacaeace

name: Deploy Jonathan Vargas Frontend
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch

  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:
    name: Build phase
    runs-on: ubuntu-latest
    env:      
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Clone repository
        id: clone-repository
        uses: actions/checkout@main
      - name: Install Node
        id: install-node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Packages
        id: install-packages          
        run: npm install          
      - name: Build project
        id: build-project
        run: npm run build
        env:
          CI: ""          
          PORT: ${{ secrets.PORT }}
          REACT_APP_ENVIRONMENT: ${{ secrets.REACT_APP_ENVIRONMENT }}
          REACT_APP_ENABLE_REDUX_DEV_TOOLS: ${{ secrets.REACT_APP_ENABLE_REDUX_DEV_TOOLS }}
          REACT_APP_ENDPOINT_PROD: ${{ secrets.REACT_APP_ENDPOINT_PROD }}
          REACT_APP_ENDPOINT_DEV: ${{ secrets.REACT_APP_ENDPOINT_DEV }}
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        id: share-artifacts
        uses: actions/upload-artifact@main
        with:
          name: react-github-actions-build
          path: build
      - uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#eventos'
        if: always()          
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:      
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      # Download previously shared build
      - name: Get artifact  
        id: get-artifacts
        uses: actions/download-artifact@main
        with:
          name: react-github-actions-build
          path: build
      # Deploy to firebase
      - name: Configure AWS Credentials
        id: configure-credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy static site to S3 bucket
        id: deploy2aws
        run: aws s3 sync ./build/ s3://${{ secrets.AWS_BUCKET_NAME }} --acl public-read

      - uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#eventos'
        if: always()

